"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import sys
from pathlib import Path

from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    h.strip()
    for h in config(
        'ALLOWED_HOSTS',
        default='localhost,127.0.0.1,.awsapprunner.com,.elb.amazonaws.com,.amazonaws.com',
    ).split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'config.apps.BigBoyAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    "corsheaders",
    "phonenumber_field",

    'bigboy.accounts.apps.AccountsConfig',
    'bigboy.subjects.apps.SubjectsConfig',
    'bigboy.sources.apps.SourcesConfig',
    'bigboy.chats.apps.ChatsConfig',
    'bigboy.quizzes.apps.QuizzesConfig',
    'bigboy.reviews.apps.ReviewsConfig',
]

MIDDLEWARE = [
    # Before CommonMiddleware: App Runner probes use Host 169.254.x.x (link-local).
    'config.middleware.AppRunnerLinkLocalHostMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_NAME = config('DATABASE_NAME', default='')
if DATABASE_NAME != '':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DATABASE_NAME,
            'USER': config('DATABASE_USER'),
            'PASSWORD': config('DATABASE_PASSWORD'),
            'HOST': config('DATABASE_HOST'),
            'PORT': int(config('DATABASE_PORT', default=5432, cast=int)),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# User-uploaded source documents (RAG)
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 'EXCEPTION_HANDLER': 'config.exceptions.custom_exception_handler',
}

# CORS settings
# https://pypi.org/project/django-cors-headers/
CORS_ALLOW_ALL_ORIGINS = True

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='memory://')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='cache+memory://')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

REDIS_PASSWORD = config('REDIS_PASSWORD', default='')
REDIS_PORT = config('REDIS_PORT', default='6379')
REDIS_HOST = config('REDIS_HOST', default='')
REDIS_USERNAME = config('REDIS_USERNAME', default='')

##############################
# DRF SPECTACULAR
#################################
SPECTACULAR_SETTINGS = {
    'TITLE': 'BigBoy API Documentation',
    'DESCRIPTION': 'BigBoy API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'email': 'developers@bigboy.com'
    },
    'SCHEMA_PATH_PREFIX': '/api/v1',
    # OTHER SETTINGS
}


################################################################# 
# Twilio settings 
##################################################################
            
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')
TO_NUMBER = config('TO_NUMBER', default='')
# TWILIO_SERVICE_SID = config('TWILIO_SERVICE_SID')


################################################################# 
# SendGrid settings 
##################################################################

# SENDGRID_API_KEY = config('SENDGRID_API_KEY')


###################################################################
#
####################################################################

META_ACCESS_TOKEN = config('META_ACCESS_TOKEN', default='')
META_PHONE_NUMBER_ID = config('META_PHONE_NUMBER_ID', default='')
META_VERIFY_TOKEN = config('META_VERIFY_TOKEN', default='')
META_API_VERSION = config('META_API_VERSION', default='')

# Standalone LangGraph research service (langgraph-service/)
LANGGRAPH_SERVICE_URL = config('LANGGRAPH_SERVICE_URL', default='')
LANGGRAPH_SERVICE_API_KEY = config('LANGGRAPH_SERVICE_API_KEY', default='')
LANGGRAPH_SERVICE_TIMEOUT = config('LANGGRAPH_SERVICE_TIMEOUT', default=120, cast=int)



################ Logging #####################
_LOG_HANDLERS = ['console', 'file'] if DEBUG else ['console']
LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": str(BASE_DIR / "general.log"),
            "formatter": "verbose",
            "level": "DEBUG",
        },
        'console': {  # This is the STDOUT handler
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            "formatter": "verbose",
            "level": "DEBUG",
            
        },
    },
    "loggers": {
        "": {
            "level": "DEBUG",
            "handlers": _LOG_HANDLERS,
        },
    },
    "formatters": {
        "verbose": {
            "format": "{name} {levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "root": {
        'handlers': ['console'],
        'level': 'DEBUG',  
    },
}
