# Generated by Django 6.0.4 on 2026-04-23 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to=settings.AUTH_USER_MODEL)),
                ('promoted_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_document_categories', to='subjects.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='sources.documentcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sources.documentchatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='McpConversationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_label', models.CharField(blank=True, help_text='Which MCP host/client produced this import, if known.', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Raw MCP / tool payload for auditing and re-processing.')),
                ('transcript', models.TextField(blank=True, help_text='Flattened or human-readable conversation text for UI and search.')),
                ('status', models.CharField(choices=[('received', 'Received'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_conversation_imports', to=settings.AUTH_USER_MODEL)),
                ('promoted_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_conversation_imports', to='subjects.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('result_blocks', models.JSONField(blank=True, default=list, help_text='Structured sections, e.g. list of {title, body} until normalized.')),
                ('graph_run_id', models.CharField(blank=True, help_text='External orchestrator / LangGraph run reference.', max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to=settings.AUTH_USER_MODEL)),
                ('promoted_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to='subjects.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(blank=True, help_text='Storage path or object key after upload (S3, local, etc.).', max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sources.documentcategory')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['account', '-created_at'], name='sources_doc_account_2b9053_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpconversationimport',
            index=models.Index(fields=['account', '-created_at'], name='sources_mcp_account_9f268a_idx'),
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['account', '-created_at'], name='sources_res_account_27becd_idx'),
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['account', 'status'], name='sources_res_account_1dc611_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['category', 'status'], name='sources_sou_categor_366c8b_idx'),
        ),
    ]
