# Generated by Django 6.0.4 on 2026-04-23 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcategory',
            name='promoted_subject',
        ),
        migrations.RemoveField(
            model_name='mcpconversationimport',
            name='promoted_subject',
        ),
        migrations.RemoveField(
            model_name='researchrun',
            name='promoted_subject',
        ),
        migrations.CreateModel(
            name='SourcePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveBigIntegerField()),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_promotions', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='sources_sou_account_49f6c2_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='sources_sou_source__0a8dbd_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='sources_sou_target__1e5eb9_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id'), name='sources_promotion_unique_source_target')],
            },
        ),
    ]
