# Generated by Django 6.0.4 on 2026-04-24 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_remove_promoted_subject_add_source_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', models.JSONField(default=list, help_text='Dense vector from Bedrock embeddings (list of floats).')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.sourcedocument')),
            ],
            options={
                'ordering': ['source_document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['source_document', 'chunk_index'], name='sources_doc_source__4d5958_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_document', 'chunk_index'), name='sources_documentchunk_source_document_chunk_index_uniq')],
            },
        ),
    ]
