# Generated by Django 6.0.4 on 2026-04-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bitereviewstate',
            new_name='reviews_bit_account_48256e_idx',
            old_name='reviews_bit_acc_next_idx',
        ),
    ]
