# Generated by Django 6.0.4 on 2026-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_bite_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bite',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When true, preserved during topic bite regeneration (human-in-the-loop).'),
        ),
    ]
